### ISSUE TITLE
stable ID question greekLit:tlg0641.tlg001 (PDL)

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-greekLit#116] opened 2016-03-03 17:17 UTC
From a user:

I am trying to embed some links for Ruldolf Hercher’s Greek text of "Xenophon of Ephesus”.  But, the stable links that are listed in the side margin do not work.  They seem to take the user to the catalogue record, not to the text itself.  I’ve listed a few of the Stable Identifiers below, so you can see what is happening.  Can you please advise if these can be fixed.

http://data.perseus.org/texts/urn:cts:greekLit:tlg0641.tlg001

http://data.perseus.org/texts/urn:cts:greekLit:tlg0641.tlg001

http://data.perseus.org/citations/urn:cts:greekLit:tlg0641.tlg001:1.1

**Comment by balmas** [comment] 2016-03-04 15:37
When we don't have the text in Perseus (or it doesn't have a CTS URN assigned to it yet in Perseus), we redirect to the Catalog.  This was done so that we can have a fall-back strategy that allows people to begin using the links now, and be assured that they will still resolve once we have the texts online.  So, a feature not a bug :)

**Comment by lcerrato** [comment] 2016-03-04 15:55
That's why I am confused: we have the text.

**Comment by balmas** [comment] 2016-03-04 16:03
oh, that's interesting.  I should have check that first. The redirects are based upon the CTS inventory as reported by Perseus 4, which for some reason is missing this text, despite the UI reporting its CTS URN. I don't really know why it's missing --  probably a big in the Perseus 4 code.

We need to revisit this whole business very soon anyway, to keep up with the progress on the CTS-izing of the texts.

**Comment by lcerrato** [comment] 2016-03-04 16:06
If the user is concerned about the short term, I don't know what to say re P4 linking, except that I don't see a fix on the horizon.

**Comment by balmas** [comment] 2016-03-04 16:07
Maybe we could tell this that we are actively working on improving and updating the data that is served by the data.perseus.org URLs and that he should feel assured that the links will continue to work and point at something useful -- the redirect to the catalog is effect working the way it was designed because it prevents us from returning a broken link when the CTS API is not able to respond for one reason or another.

**Comment by balmas** [comment] 2016-03-04 16:08
I realize it's a little less than satisfactory but I think what this request does do is remind us that we need to take a look at updating the data.perseus.org handling sooner rather than later.

**Comment by lcerrato** [comment] 2016-03-04 16:12
Great, thanks!

**Closed** 2016-03-04 16:24 UTC
Labels: question
